### ISSUE TITLE
sign_url async API

### ISSUE THREAD

**Issue by jhagege** [Jerevia/asyncoss#3]
Hi, looks great, thanks! 
Any way to add support for sign_url method to asyncio API ?

**Comment by Jerevia** [comment]
Sorry for taking so long to reply.
The answer is, you don't need an async `sign` method. Actually, the `sign_url` method only "sign" url, it doesn't send any real requests to the OSS.

**Comment by jhagege** [comment]
Thanks for the answer, makes sense.
